### ISSUE TITLE
not working with kofi-table-1.0.3+1.19.x.jar

### ISSUE THREAD

**Issue by nickademas** [AmyMialeeMods/peculiar-pieces#2]
[latest.log](https://github.com/AmyMialeeMods/peculiar-pieces/files/9402152/latest.log)

**Comment by AmyMialee** [comment]
that's weird, it works for me with a fresh download.
try re-downloading kofi-table, in case it was corrupted somehow during downloading.
https://cdn.modrinth.com/data/ycUyVm1V/versions/1.0.3+1.19.x/kofi-table-1.0.3%2B1.19.x.jar

**Comment by AmyMialee** [comment]
actually it turns out it was the *upload* on curseforge
gonna reupload it

**Comment by AmyMialee** [comment]
thanks curseforge for approving a failed upload so i don't realise anything is wrong for ages
