### ISSUE TITLE
Visibility of placed barriers when item form is held

### ISSUE THREAD

**Issue by MerchantPug** [AmyMialeeMods/peculiar-pieces#21]
Please do something similar to vanilla barriers with your barriers where you can see them if you're holding the item form of the block. This'd be immensely helpful when building with them.

**Comment by AmyMialee** [comment]
I could but it would mean that every time you start holding the item or put it away it'll do the F3+A thing that the keybind does already.

Also wrong mod (Visible Barriers is what'd need the change) but I do both so it's fine.

**Comment by MerchantPug** [comment]
My bad.

**Comment by MerchantPug** [comment]
I'll close this issue to get it on the correct repo

**Comment by MerchantPug** [comment]
Ah I meant the gamemode barriers which are part of this mod

**Comment by AmyMialee** [comment]
> Ah I meant for the gamemode barriers which are part of this mod to sorta replicate vanilla behavior, no need to do the change to Visible Barriers as the refresh would be mega annoying.

yea but why would i add the feature for those when i could just make it part of vb and then set it up for this one as part of that

**Comment by MerchantPug** [comment]
If it's not feasible or if that implementation in vanilla is laggy, feel free to not do it.

**Comment by MerchantPug** [comment]
Alright okay. Cool.
