### ISSUE TITLE
Can't access any block inventories?

### ISSUE THREAD

**Issue by Kadynsr** [AmyMialeeMods/peculiar-pieces#3]
I can't seem to be able to access any of the block inventories? equipment stand doesn't work, fish tank, potion pad, nothing like that works. I can still get into the dropper and barrels and stuff

**Comment by AmyMialee** [comment]
are you holding shift?

**Comment by Kadynsr** [comment]
yep, tried everything I could

**Comment by AmyMialee** [comment]
that's weird, are you in adventure mode? they're typically locked to adventure mode players.
otherwise it's just shift right click.

**Comment by Kadynsr** [comment]
Nope, survival, creative, nothin, regular right click, shift right click, left click, bash my head against the keyboard XD nothing

**Comment by AmyMialee** [comment]
That's very weird, what's the mod list?

**Comment by Kadynsr** [comment]
![1](https://user-images.githubusercontent.com/54544306/187286345-45387712-1870-4131-8504-e6f14952cb43.png)
![2](https://user-images.githubusercontent.com/54544306/187286366-55236b6d-6a6d-4865-9233-3092e7035f5a.png)
![3](https://user-images.githubusercontent.com/54544306/187286374-0570d485-6444-4188-a331-61e411ac334f.png)
![4](https://user
![5](https://user-images.githubusercontent.com/54544306/187286391-22926023-e389-4724-a193-89eb87e8beb1.png)
-images.githubusercontent.com/54544306/187286384-c7e96bc4-28ab-4506-9540-de54feff2d1a.png)
![6](https://user-images.githubusercontent.com/54544306/187286397-7ab5f80c-c3b4-47f1-800b-237a385935d8.png)
![7](https://user-images.githubusercontent.com/54544306/187286406-83db23f7-7573-46c1-9c3b-43e26e7e7698.png)

**Comment by AmyMialee** [comment]
oh that is uh quite a lot, could you export it as a modpack in whatever launcher you use so i could look at it?
it would take a while though, if you want to try yourself you can try making a new world and just removing half the mods and seeing if it's fixed, and then adding stuff back in half by half until you find what's causing problems.

**Comment by Kadynsr** [comment]
Ok so it seems that it is nyfsquiver mod? Odd

**Comment by AmyMialee** [comment]
that's very weird, not sure what they could be doing to cause that.
