### ISSUE TITLE
Checkpoints Don't Work Interdimensionally

### ISSUE THREAD

**Issue by SylvKT** [AmyMialeeMods/peculiar-pieces#6]
### Description
When setting a checkpoint in one dimension (ex. the overworld), going into another dimension (ex. the end), then stepping on a Checkpoint Returner:tm:, it will teleport you to the coordinates of the checkpoint in the first dimension (ex. the overworld) in the second dimension (ex. the end).

**Comment by AmyMialee** [comment]
fixed in next update
