### ISSUE TITLE
[Bug] Item Duplication with the Bundle Item

### ISSUE THREAD

**Issue by mmmmmabil** [AmyMialeeMods/peculiar-pieces#7]
i forgot how it is called but once u have one of them u can easily duplicate any item that u can insert in it

the dupe is ridiculously easy to do
u just put whatever item u want to dupe in the bundle, throw it out and then take the item(s) out of the inventory 
then u can just pick the bunlde back up put the duped items inside and repeat as many times as ud like

**Comment by mmmmmabil** [comment]
pouch i believe its called

**Comment by AmyMialee** [comment]
going to be fixed in the next release
